[package]
name = "vidya-db"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
r2d2.workspace = true
r2d2_sqlite.workspace = true
serde_json.workspace = true
thiserror.workspace = true
vidya-core = { path = "../vidya-core" }
zeroize.workspace = true

[target.'cfg(target_vendor = "apple")'.dependencies]
rusqlite = { workspace = true, features = ["bundled-sqlcipher"] }

[target.'cfg(not(target_vendor = "apple"))'.dependencies]
rusqlite = { workspace = true, features = ["bundled-sqlcipher-vendored-openssl"] }

[dev-dependencies]
tempfile.workspace = true
